### ISSUE TITLE
Allow to set error handler for worker

### ISSUE THREAD

**Issue by mxmCherry** [bsm/fleiss#19]
To capture/handle/notify about exceptions (sentry etc).

Like:

```ruby
# config/initializer/fleiss.rb:
Fleiss::Worker.on_error do |err|
  Sentry.report(err) # pseudocode
  raise # maybe this wouldn't work, maybe just return bool to suppress/re-raise to keep backtrace?
end

# OR maybe (even better) smth like:
Fleiss::Worker.around_perform do
  yield
recue StandardError => err # can even filter errors by type
  Sentry.report(err) # pseudocode
  raise
end
```

Then run it like:

```shell
bundle exec fleiss -I . -r config/initializers/sentry -r config/initializers/fleiss.rb
```

**Comment by mxmCherry** [comment]
@dim suggest?

**Comment by dim** [comment]
`around_perform` is probably better as it allows you to instrument it too, but I wonder if we should just use `ActiveSupport::Notifications` instead ala https://github.com/lintci/sidekiq-notifications/blob/master/lib/sidekiq/notifications/server_middleware.rb

**Comment by mxmCherry** [comment]
@dim that's also fine and maybe not a concern as Fleiss already uses ActiveRecord (and I'm quite certain it has Notifications as a dep). Or we could do it with `if defined?(ActiveSupport::Notifications)`, not a problem.

I'm not totally opposed to Notifications, but I find it slightly less explicit than around_perform (though should be much easier to plug Notifications in).

The only functional difference is that client may opt to ignore some errors, which is not possible with Notifications - should we bother though? `err.backtrace` won't be lost either way (maybe will not contain anything extra when done with Notifications).

**Comment by dim** [comment]
We already require `activejob` which requires `activesupport` so `defined?(ActiveSupport::Notifications)` will always be `true`. ActiveJob as instrumentation already https://guides.rubyonrails.org/active_support_instrumentation.html#active-job but we want to add one more level above that to catch errors that happen before AJ is involved.

**Comment by mxmCherry** [comment]
Ok, Notifications then. No need to bother with around_perform and error handling (suppressing) by caller.
